name: Validate bicep scripts
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI script
        uses: azure/CLI@v2
        with:
          inlineScript: az bicep lint --file infra/main.bicep --diagnostics-format sarif > bicep-results.sarif
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bicep-results.sarif
